language: php
 
php:
  - 5.5
  - 5.6
  - hhvm
 

before_install:
- composer require phpunit/phpunit satooshi/php-coveralls:dev-master
- composer install --dev
 
script:
- ./vendor/bin/phpunit --coverage-clover ./tests/reports/coverage.xml
 
after_script:
- php vendor/bin/coveralls -v
